// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCore_MVC_RateBoard.Models;

namespace WebCore_MVC_RateBoard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200130084240_SeedDataInOldDB")]
    partial class SeedDataInOldDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebCore_MVC_RateBoard.Models.BackScreenRateSql", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("backImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("backRate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("backScreenRates");
                });

            modelBuilder.Entity("WebCore_MVC_RateBoard.Models.RateModelSql", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCBuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCSale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TFRate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("rateModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Country = "USA",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/USA.png",
                            TFRate = "56"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AUD",
                            Country = "AUSTRALIA",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/AUSTRALIA.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GBP",
                            Country = "BRITAN",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/GB.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 4,
                            Code = "BHD",
                            Country = "BAHRAIN",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/BAHRAIN.jpg",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BDT",
                            Country = "BANGLADESH",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/BDT.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CAD",
                            Country = "CANADA",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/CANADA.jpg",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 7,
                            Code = "EUR",
                            Country = "EURO",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/EURO.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 8,
                            Code = "EGP",
                            Country = "EGYPT",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/EGYPT.jpg",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 9,
                            Code = "INR",
                            Country = "INDIA",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/INDIA.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 10,
                            Code = "KWD",
                            Country = "KUWAIT",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/KUWAIT.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 11,
                            Code = "NPR",
                            Country = "NEPAL",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/NEPAL.jpg",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 12,
                            Code = "OMR",
                            Country = "OMAN",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/OMAN.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 13,
                            Code = "PHP",
                            Country = "PHILIPPINES",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/PHP.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 14,
                            Code = "PKR",
                            Country = "PAKISTAN",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/PAK.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 15,
                            Code = "CHF",
                            Country = "SWISS",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/SWISS.png",
                            TFRate = "45"
                        },
                        new
                        {
                            Id = 16,
                            Code = "SAR",
                            Country = "SAUDIA",
                            FCBuy = "3.67",
                            FCSale = "3.68",
                            Image = "~/Images/SAUDI.png",
                            TFRate = "45"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
